### ISSUE TITLE
Typo in example sketch serial output

### ISSUE THREAD

**Issue by djoe-branch** [adafruit/Adafruit_PM25AQI#4]
Typo in the example sketch referencing '50 um' particles instead of '10 um.' Great starter sketch otherwise.

Line 68 of /examples/PM25_test/PM25_test.ino :
`Serial.print(F("Particles > 50 um / 0.1L air:")); Serial.println(data.particles_100um);`

Should read :
`Serial.print(F("Particles > 10 um / 0.1L air:")); Serial.println(data.particles_100um);`

**Comment by ladyada** [comment]
thanks, can you submit a PR change?
