### ISSUE TITLE
Header file needs #include guards

### ISSUE THREAD

**Issue by BriscoeTech** [adafruit/Adafruit_PM25AQI#6]
Hello Everyone,

I discovered the library is missing its #include guards, this can lead to the compiler thinking there are multiple definitions of the objects depending on how your project is organized.

Here is what I did to fix it in the Adafruit_PM25AQI.h

![image](https://user-images.githubusercontent.com/23386254/100560030-5a210380-3269-11eb-809b-6eb0ab1be49a.png)

**Comment by ladyada** [comment]
thanks, please submit a PR if you can!
https://learn.adafruit.com/contribute-to-arduino-with-git-and-github
